name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    id: preface
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    id: environment
    attributes:
      value: "## Environment"
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What is version of KubeKey has the issue?
      description: "You can use the command to get `./kk version`"
  - type: input
    id: os
    validations:
      required: true
    attributes:
      label: What is your os environment?
      description: "e.g. Ubuntu 16.04"
  - type: textarea
    id: config
    attributes:
      label: KubeKey config file
      description: "If applicable, add the KubeKey config file content to help explain your problem."
      render: yaml
  - type: markdown
    id: main
    attributes:
      value: "## Main"
  - type: textarea
    id: what
    validations:
      required: true
    attributes:
      label: A clear and concise description of what happend.
  - type: textarea
    id: logs
    attributes:
      label: "Relevant log output"
      description: "Please copy and paste any relevant log output."
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: "Additional information"
      description: "Add any other context about the information here (screenshots, video, etc.)."