blank_issues_enabled: false
contact_links:
  - name: Any other questions about KubeKey
    url: https://kubesphere.slack.com/
    about: If you have any other questions, you can join our slack channel.