name: Feature Request
description: File a feature request
body:
  - type: markdown
    id: preface
    attributes:
      value: "Thank you for submitting new features for KubeKey."
  - type: markdown
    id: environment
    attributes:
      value: "## Environment"
  - type: input
    id: version
    attributes:
      label: "Your current KubeKey version"
      description: "You can use the command to get `./kk version`"
  - type: markdown
    id: main
    attributes:
      value: "## Main"
  - type: textarea
    id: description
    attributes:
      label: "Describe this feature"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "You can have a concise description of any alternative solutions or ideas you've considered."
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: "Additional information"
      description: "Add any other context about the information here (screenshots, video, etc.)."