---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: kube-system
type: kubernetes.io/glusterfs
data:
  # e.g. jwt_admin_key: 123456
  key: SHOULD_BE_REPLACED

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  glusterfs
  annotations:
    storageclass.kubesphere.io/supported-access-modes: '["ReadWriteOnce","ReadOnlyMany","ReadWriteMany"]'
    # default storage
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/glusterfs
parameters:
  # e.g. glusterfs_provisioner_resturl: http://192.168.0.4:8080
  resturl: SHOULD_BE_REPLACED
  # e.g. glusterfs_provisioner_clusterid: 6a6792ed25405eaa6302da99f2f5e24b
  clusterid: SHOULD_BE_REPLACED
  restauthenabled: "true"
  restuser: admin
  secretNamespace: "kube-system"
  secretName: heketi-secret
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "replicate:2"
allowVolumeExpansion: true